### ISSUE TITLE
Semantic versioning doesn't seem to work for Chef-Zero

### ISSUE THREAD

**Issue by ABrehm264** [chef/chef-zero#159] opened 2015-08-18 19:07 UTC
Info:
$ chef-zero version
>> Starting Chef Zero (v4.2.1)...
>> WEBrick (v1.3.1) on Rack (v1.5) is listening at http://127.0.0.1:8889
>> Press CTRL+C to stop

Error for a cookbook with version "4.1.2.alpha1"
[2015-08-18T15:05:12-04:00] ERROR: #<ArgumentError: Malformed version number string 4.1.2-alpha1>
C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/version.rb:187:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `block in filter_by_constraint'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `select'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `filter_by_constraint'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:95:in `block (2 levels) in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:81:in `each_pair'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:81:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_base.rb:29:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_router.rb:23:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/server.rb:369:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.

Server Response:
----------------
Exception raised!  #<ArgumentError: Malformed version number string 4.1.2-alpha1>
C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/version.rb:187:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `block in filter_by_constraint'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `select'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:116:in `filter_by_constraint'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:95:in `block (2 levels) in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:81:in `each_pair'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:81:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_base.rb:29:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_router.rb:23:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/server.rb:369:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

Error for a cookbook with version "4.1.2.a1"
[2015-08-18T14:53:05-04:00] ERROR: #<NoMethodError: undefined method `to_hash' for nil:NilClass>
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:85:in `block in get'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:339:in `with_entry'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:82:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_base.rb:42:in `get_data'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:77:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_base.rb:29:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_router.rb:23:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/server.rb:369:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.

Server Response:
----------------
Exception raised!  #<NoMethodError: undefined method `to_hash' for nil:NilClass>
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:85:in `block in get'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:339:in `with_entry'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4-x86-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:82:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_base.rb:42:in `get_data'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:77:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:101:in `block in depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:71:in `depsolve'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/endpoints/environment_cookbook_versions_endpoint.rb:37:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_base.rb:29:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/rest_router.rb:23:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-zero-2.0.2/lib/chef_zero/server.rb:369:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
C:/opscode/chef/embedded/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

Both of which should work with semantic versioning:
http://semver.org/

**Comment by thommay** [comment] 2016-07-29 09:09
Hi,
Sorry for the slow response. Cookbook versioning is not completely compatible with semver, in that it does not support pre releases or non-numbers in versions; please see https://docs.chef.io/cookbook_versions.html#syntax for details.
Since this is by design, I'm going to close this issue.
Thanks for the report!
-Thom

**Closed by thommay** 2016-07-29 09:09 UTC
